<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\Trivo.Application\Trivo.Application.csproj" />
      <ProjectReference Include="..\..\Domain\Trivo.Domain\Trivo.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CloudinaryDotNet" Version="1.27.0" />
      <PackageReference Include="MailKit" Version="4.12.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
      <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.3" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
      <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.10.0" />
      <PackageReference Include="MimeKit" Version="4.12.0" />
      <PackageReference Include="OpenAI" Version="2.12.0" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.10.0" />
    </ItemGroup>

</Project>
